        - name: varify NodeJS
          ansible.builtin.shell: type npm
          register: npm
          ignore_errors: true

        - name: nodejs:1
          ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
          when: npm.rc != 0

        - name: install Nodjs
          ansible.builtin.dnf:
            name: nodejs
          when: npm.rc != 0

        - name: Copy Backend service file
          ansible.builtin.template:
            src: backend.service
            dest: /etc/systemd/system/backend.service

        - name: Add application User
          ansible.builtin.user:
            name: expense

        - name: Cleanup old Content
          ansible.builtin.file:
            path: /app
            state: absent

        - name: create app directory
          ansible.builtin.file:
            path: /app
            state: directory

        - name: Download and extract backend file
          ansible.builtin.unarchive:
            src: https://expense-artifacts.s3.amazonaws.com/backend.zip
            dest: /app
            remote_src: yes

        - name: Install New Relic NodeJS Library
          ansible.builtin.shell: npm install
          args:
            chdir: /app

        - name: install mysql
          ansible.builtin.dnf:
            name: mysql

        - name: Load schema
          ansible.builtin.shell: mysql -h {{ lookup('amazon.aws.aws_ssm', 'expense.frontend.my_db', region='us-east-1' ) }} -uroot -p{{ lookup('amazon.aws.aws_ssm', 'paas_exp', region='us-east-1' ) }} < /app/schema/backend.sql

        - name: start backend service
          ansible.builtin.systemd:
            name: backend
            state: restarted
            enabled: true
            daemon-reload: yes
        - name: Install Node Exporter
          ansible.builtin.import_role:
            name: prometheus
            tasks_from: node-exporter